CREATE TABLE GOYA.UNIDAD_ESTRUCTURAL
(
  ID_UNIDAD       NUMBER(10),
  CODIGO_G        VARCHAR2(8 BYTE),
  DES_UNIDAD      VARCHAR2(100 BYTE)            NOT NULL,
  ID_RESPONSABLE  NUMBER(10),
  COD_NIVEL       NUMBER(2)                     NOT NULL,
  ID_PADRE        NUMBER(10),
  ID_PADRE1       NUMBER(10),
  ID_PADRE2       NUMBER(10),
  ID_PADRE3       NUMBER(10),
  ID_JERARQUIA    NUMBER(10),
  CHK_ACTIVO      NUMBER,
  FE_CREA_REG     DATE,
  FE_MODI_REG     DATE,
  COD_MOD_USU     VARCHAR2(8 BYTE),
  ID_PADRE4       NUMBER(10),
  COD_ORDEN       NUMBER
)
/

CREATE UNIQUE INDEX GOYA.UNIDAD_ESTRUCTURAL_PK ON GOYA.UNIDAD_ESTRUCTURAL (ID_UNIDAD)
/
ALTER TABLE GOYA.UNIDAD_ESTRUCTURAL ADD (CONSTRAINT UNIDAD_ESTRUCTURAL_PK  PRIMARY KEY  (ID_UNIDAD))
/

CREATE TABLE GOYA.PERSONAL_NEW
(
  ID_PERSONAL      NUMBER(10)                   NOT NULL,
  COD_SILCON       CHAR(8 BYTE)                 NOT NULL,
  COD_DNI          VARCHAR2(9 BYTE)             NOT NULL,
  DES_NOMBRE       VARCHAR2(100 BYTE)           NOT NULL,
  DES_APELLIDOS    VARCHAR2(250 BYTE)           NOT NULL,
  FE_ALTA          DATE                         NOT NULL,
  FE_BAJA          DATE,
  NUM_TELEFONO     NUMBER(9),
  NUM_MOVIL        NUMBER(9),
  ID_UBICACION     NUMBER(10),
  DES_FUNCION      VARCHAR2(2000 BYTE),
  ID_CONTRATO      NUMBER(10),
  ID_LOTE          NUMBER(10),
  ID_TURNO         NUMBER(10),
  ID_EMPRESA       NUMBER(10),
  ID_EMPRESA_REAL  NUMBER(10),
  ID_CATEGORIA     NUMBER(10),
  ID_COMISION      NUMBER(10),
  ID_DESEMPENO     NUMBER(10),
  COD_GRUPO        VARCHAR2(5 BYTE),
  ID_ESTATUS       NUMBER(10),
  CHK_ARTEMIS      CHAR(1 BYTE),
  ID_UNIDAD        NUMBER(10),
  COD_JERARQUIA    NUMBER(2),
  CHK_ACTIVO       CHAR(1 BYTE),
  ID_PERFIL        NUMBER(10),
  FE_CREA_REG      DATE                         NOT NULL,
  FE_MODI_REG      DATE                         NOT NULL,
  COD_USU_MOD      VARCHAR2(8 BYTE)             NOT NULL
)
/

CREATE UNIQUE INDEX GOYA.PERSONAL_NEW_PK ON GOYA.PERSONAL_NEW (ID_PERSONAL)
/
ALTER TABLE GOYA.PERSONAL_NEW ADD (CONSTRAINT PERSONAL_NEW_PK PRIMARY KEY  (ID_PERSONAL))
/