CREATE TABLE GOYA.TIPO_PROC_ADJ
(
  ID_PROC_ADJ   NUMBER                          NOT NULL,
  COD_PROC_ADJ  VARCHAR2(10 BYTE)               NOT NULL,
  DES_PROC_ADJ  VARCHAR2(255 BYTE)              NOT NULL,
  CHK_ACTIVO    NUMBER                          NOT NULL,
  FE_CREA_REG   DATE,
  FE_MODI_REG   DATE,
  COD_MOD_USU   VARCHAR2(8 BYTE)
)
/

CREATE UNIQUE INDEX GOYA.TIPO_PROC_ADJ_PK ON GOYA.TIPO_PROC_ADJ (ID_PROC_ADJ)
/

ALTER TABLE GOYA.TIPO_PROC_ADJ ADD (CONSTRAINT TIPO_PROC_ADJ_PK PRIMARY KEY (ID_PROC_ADJ))
/