create table V_ESTRUCTURA_CENTRO
(
  ID_UNIDAD    NUMBER(10),
  NIVEL        NUMBER(2),
  JERARQUIA    NUMBER(10),
  DEPARTAMENTO VARCHAR2(100),
  UNIDAD       VARCHAR2(100),
  GRUPO        VARCHAR2(100),
  SUBGRUPO     VARCHAR2(100),
  TURNO        VARCHAR2(100)
);
